import { OutputPort } from '@lights/io';

/**
 * Interface representing a driver that generates frames.
 * A driver is essentially a source of frames (like a hardware input or a timer).
 * @interface BaseDriverInterface
 * @property {OutputPort} output - Output port emitting generated frames
 */
export interface BaseDriverInterface {
  /**
   * Output port emitting frames generated by the driver.
   */
  output: OutputPort;
  /**
   * Starts the driver.
   */
  start(): void;
  /**
   * Stops the driver.
   */
  stop(): void;
}

/**
 * Base implementation of a driver.
 * It provides a source of frames through an output port.
 *
 * @property {OutputPort} output - The output port emitting frames
 */
export abstract class BaseDriver implements BaseDriverInterface {
  /**
   * Output port emitting frames generated by the driver.
   */
  readonly output: OutputPort = new OutputPort();

  /**
   * Starts the driver.
   */
  public abstract start(): void;

  /**
   * Stops the driver.
   */
  public abstract stop(): void;
}
