import { Observable } from 'rxjs';
import { Frame } from '@lights/io';

/**
 * Interface representing a driver that generates frames.
 * A driver is essentially a source of frames (like a hardware input or a timer).
 * @interface BaseDriverInterface
 * @property {Observable<Frame>} output$ - Observable stream of generated frames
 */
export interface BaseDriverInterface {
  /**
   * Observable stream of frames.
   */
  output$: Observable<Frame>;
  /**
   * Starts the driver.
   */
  start(): void;
  /**
   * Stops the driver.
   */
  stop(): void;
}

/**
 * Base implementation of a driver.
 * It provides a source of frames.
 * 
 * @property {Observable<Frame>} output$ - The resulting stream of frames
 */
export abstract class BaseDriver implements BaseDriverInterface {
  /**
   * Observable stream of frames generated by the driver.
   */
  public abstract output$: Observable<Frame>;

  /**
   * Starts the driver.
   */
  public abstract start(): void;

  /**
   * Stops the driver.
   */
  public abstract stop(): void;
}
